"use strict";
exports.__esModule = true;
var message = 'Welcome back';
console.log(message);
var x = 10;
var y = 20;
var title = 'codevolution';
//variable types boolean,number,string
var isBeginner = true;
var total = 0;
var Name = 'Rose';
var sentence = "my name is ".concat(Name, " I am a biginner in Typescript");
console.log(sentence);
var n = null;
var u = undefined;
var isNew = true;
var myName = 'Carly';
var list1 = [1, 2, 3];
var list2 = [1, 2, 3];
var person = ['chris', 22];
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
;
var c = Color.Blue;
console.log(c);
var randomvalue = 10;
randomvalue = true;
randomvalue = 'vishwas';
